apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginxapp-deploy
spec:
  selector:
    matchLabels:
      app: nginx
  replicas: 2 
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginxappcont
        image: jaggu199/nginxapp:1.1
        ports:
        - containerPort: 80
