---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: nginx
  name: svc-demo-nodeport
spec:
  type: NodePort
  ports:
  - port: 80
    targetPort: 80
    nodePort: 30080
  selector:
    app: nginx
