---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: nginx
  name: svc-demo-loadbalancer
spec:
  selector:
    app: nginx
  type: LoadBalancer
  ports:
  - protocol: TCP
    port: 80
    targetPort: 9376
status:
  loadBalancer:
    ingress:
    - ip: 192.0.2.127
